### PR TITLE
Update patterns and example app

### PR DESCRIPTION
**Pull request by nathany**
* Update credo
* Run `mix format`
* Update GitHub URL to beam-community
  * Travis CI needs to be updated though https://travis-ci.org/beam-community/ua_parser
* Update patterns from BrowserScope’s uap-core
* Update example app to Phoenix 1.4

### CODE REVIEW

**Comment by doomspork** [comment]
@nathany I have moved this repo, along with some others, to a new org dedicated to supporting Elixir/Erlang packages. Since you're a contributor to this project already, would you be interested in joining the larger @beam-community/team? 😀

**Comment by nathany** [comment]
@doomspork Absolutely interested.

Any idea what needs to be done in Travis CI to get it running again since the move?

**Comment by doomspork** [comment]
@nathany it should be setup now, can you push a change?

**Comment by nathany** [comment]
Yup, Travis CI is running. Thanks

**Comment by doomspork** [comment]
Great. You've also been invited to the org 😁

**Comment by doomspork** [comment]
@nathany this looks good to me, one question though: do we want to keep the example app in the repo or create a new repo for it?

**Comment by nathany** [comment]
@doomspork Good question. I think it's fine like this because the `files` in `mix.exs` doesn't include the example, so the hex package won't be any bigger either way.

If you'd like a separate repo though, I'd be happy to set that up. `ua_parser_example`?

**Comment by doomspork** [comment]
We can keep in the repo, that's a good point 😁

**Comment by doomspork** [comment]
@nathany if you'd like to open up a PR to bump the version/changelog we can cut a new release. I can also get you added to hex if I hadn't already

**Comment by nathany** [comment]
@doomspork Will do. My hex user is https://hex.pm/users/nathan

**Comment by doomspork** [comment]
@nathany you've been added to the hex repo. Thanks again for all your help, really fortunate to help you 😁

**Pull request merged**
