### PR TITLE
Update patterns from BrowserScope

### PR DESCRIPTION
**Pull request by nathany**
source: https://github.com/ua-parser/uap-core/blob/master/regexes.yaml

### CODE REVIEW

**Comment by nathany** [comment]
The tests pass locally with Elixir 1.11.3. I'm adding newer versions of Elixir and Erlang to Travis CI to see if it passes.

**Comment by doomspork** [comment]
We could (and maybe should) move this to Github Actions. What do you think @nathany ?

**Comment by nathany** [comment]
Hi Sean! Yes, I could open a separate pull request to use GitHub Actions and then come back to this patterns update after.

How many versions back should we run the tests on? https://github.com/actions/setup-elixir#matrix-example

**Comment by nathany** [comment]
Hi Sean! Yes, I could open a separate pull request to use GitHub Actions and then come back to this patterns update after.

How many versions back should we run the tests on? https://github.com/actions/setup-elixir#matrix-example

**Comment by nathany** [comment]
@doomspork I'm not sure why the tests pass locally for me but fail in CI.

**Comment by doomspork** [comment]
Hmm. @nathany I'll take a look and see if I can track it down :thinking:

**Comment by taj** [comment]
Looks like they've improved the patterns and made the devices more recognisable to me! :) 
So I've pushed a change to fix the tests

**Comment by nathany** [comment]
Thanks Tajinder

**Review by doomspork — APPROVED** [review]

**Comment by doomspork** [comment]
@taj do you have permissions to release this on Hex?

**Comment by taj** [comment]
@doomspork no I do not :)

**Pull request merged**
