### PR TITLE
Release 1.7.0

### PR DESCRIPTION
**Pull request by nathany**
* New release includes the latest pattern file
* Update GitHub URL to beam-community organization
* Update example app to Phoenix 1.4

### CODE REVIEW

**Comment by nathany** [comment]
Is 1.7.0 a suitable version for this release?

**Comment by doomspork** [comment]
@nathany do we have any breaking changes? I don't _think_ so, in which case I think 1.7 is perfectly okay.

**Comment by doomspork** [comment]
@nathany please do add yourself as a maintainer, you should absolutely get recognized for help 😁

**Comment by nathany** [comment]
No breaking changes.

**Comment by nathany** [comment]
Thanks Sean. I've added myself as a maintainer and published 1.7.

**Comment by doomspork** [comment]
Awesome! Thank _you_ @nathany! I'm excited to get the chance to work with you, even in a limited capacity 😁 

I hope you and your's have a wonderful weekend

**Pull request merged**
